name: Fantasy Robot Fighter
description: Short Swords & Short Circuits
meta_description: "Hacking and rewiring tabletop role-playing games."

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'https://fantasyrobotfighter.github.io'
google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://www.fantasyrobotfighter.com'
author:         'Fantasy Robot Fighter'
authorTwitter:  'fantasybotfight'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post