name: Fantasy Robot Fighter, a blog about RPGs and SEO
description: Short Swords & Short Circuits
meta_description: "A blog where I share my RPG hacks and talk about search engine optimization (SEO) for independent game designers."

aboutPage: true

markdown: kramdown
highlighter: rouge

plugins: [jekyll-paginate]
paginate: 20
domain_name: 'https://fantasyrobotfighter.github.io'
google_analytics: 'UA-74510536-3'
disqus: true
disqus_shortname: 'fantasyrobotfighter'

# Details for the RSS feed generator
url:            'https://www.fantasyrobotfighter.com'
author:         'Fantasy Robot Fighter'
authorTwitter:  'fantasybotfight'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post